# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHnqffJKSKtY9iX1CSuVrvnemLT0ngWa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.metrics import accuracy_score,classification_report

"""# New Section"""

import pandas as pd

df = pd.read_csv("/content/bank-additional-full.csv", sep=";")

df.head()

print(df.shape)

df.info()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure()

sns.countplot(x='y', data=df)

plt.title("Customer Purchase Distribution")

plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = le.fit_transform(df[col])

from sklearn.model_selection import train_test_split

X = df.drop("y", axis=1)

y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    random_state=42
)

model.fit(
    X_train,
    y_train
)

pred = model.predict(X_test)

from sklearn.tree import plot_tree

plt.figure(figsize=(20,10))

plot_tree(
    model,
    filled=True,
    feature_names=X.columns,
    max_depth=3
)

plt.show()